name: CI
on:
  push:
    branches: [demo-2]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: pokeoctober
      - name: Checkout an old pokecrystal commit
        # can't get actions/checkout to check an old commit...
        run: |
          git clone https://github.com/pret/pokecrystal
          cd pokecrystal
          git checkout 6f226f584c
      - name: Checkout rgbds
        uses: actions/checkout@v4
        with:
          path: rgbds
          ref: v0.4.1
          repository: gbdev/rgbds
      - name: Install rgbds
        working-directory: rgbds
        run: |
          sudo make install
      - name: Make pokecrystal (as baserom)
        working-directory: pokecrystal
        run: |
          make -j$(nproc) pokecrystal11.gbc
      - name: Make pokeoctober
        working-directory: pokeoctober
        run: |
          cp ../pokecrystal/pokecrystal11.gbc baserom.gbc
          make -j$(nproc) pokeoctober-v.`git describe --always --abbrev=8 --dirty='!' | 
awk -F "-" '{print $1}'`.ips
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: patch
          path: |
            pokeoctober/*.ips
